// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKd6p9JN6iP-o_Q7xFQ1nWnTdDLl6Tc4Q',
    appId: '1:1059746460228:web:4cccae898447d765c58211',
    messagingSenderId: '1059746460228',
    projectId: 'guideme-through',
    authDomain: 'guideme-through.firebaseapp.com',
    storageBucket: 'guideme-through.appspot.com',
    measurementId: 'G-YJT5DLP08X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApcKt-avNCe65liCKGl9RwslsIwmvCeAs',
    appId: '1:1059746460228:android:ae065357df3a3a43c58211',
    messagingSenderId: '1059746460228',
    projectId: 'guideme-through',
    storageBucket: 'guideme-through.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_2XJQKD5jbAh_fMRIXu32GDnY5lafes',
    appId: '1:1059746460228:ios:8192d40ddea8d548c58211',
    messagingSenderId: '1059746460228',
    projectId: 'guideme-through',
    storageBucket: 'guideme-through.appspot.com',
    iosClientId: '1059746460228-oi1o357m619di2k790mvp2irjupf2k3l.apps.googleusercontent.com',
    iosBundleId: 'com.pavan72362.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_2XJQKD5jbAh_fMRIXu32GDnY5lafes',
    appId: '1:1059746460228:ios:8192d40ddea8d548c58211',
    messagingSenderId: '1059746460228',
    projectId: 'guideme-through',
    storageBucket: 'guideme-through.appspot.com',
    iosClientId: '1059746460228-oi1o357m619di2k790mvp2irjupf2k3l.apps.googleusercontent.com',
    iosBundleId: 'com.pavan72362.code',
  );
}
